### ISSUE TITLE
Interactive Grid Issue perhaps?

### ISSUE THREAD

**Issue by aldocano29** [RonnyWeiss/APEX-Monaco-Editor-and-Diff-Viewer#1]
When there's an IG on the same page, the region doesnt load at all. Maybe it has to do with the js that runs on the IG

**Comment by RonnyWeiss** [comment]
Hello 

Thank you for that! I've fixed that in new Version 1.02.

Have fun with the plugin and a nice weekend

Kind regards

Ronny
