### ISSUE TITLE
Plain Text Source Error

### ISSUE THREAD

**Issue by aldocano29** [RonnyWeiss/APEX-Monaco-Editor-and-Diff-Viewer#2]
Hello, when I specify in Standard Attributes that the region source is plain text, the plugin throws an error on the page where it is implemented.

What could be the issue?
![Screen Shot 2021-05-07 at 9 58 41 AM](https://user-images.githubusercontent.com/20285968/117468937-cee42200-af1a-11eb-98a8-bd20bdc82862.png)

**Comment by RonnyWeiss** [comment]
Hello 

You can not set plain text. Which APEX Version do you use? 

Only SQL Query is set in the plug-in as source and in App Builder you can only set sql query so how could you set plain text?

regards

Ronny

**Comment by aldocano29** [comment]
Hello, I’m using apex 19.2 and 20.2. Inside the plugin’s settings there is an option that lets you enable plain text (the default is a query, and also other sources)

That is why I assumed it was possible.

Aldo Cano

**Comment by RonnyWeiss** [comment]
Hello you can Not change any setting or Code on the plugin and think that will work.

But why Do you need plain Text? You can easily Set a static Text from dual in the SQL Query. So I dont understand the use case 😉

Kind regards

Ronny

**Comment by aldocano29** [comment]
Hello,

I changed it because the option is available in the settings, so if it exist I assumed it should work.

Here is the screenshot that shows the option in the plugin settings:


![Screen Shot 2021-05-08 at 9 06 18 AM](https://user-images.githubusercontent.com/20285968/117542098-cbb16a80-afdc-11eb-846b-417c6925cfd0.png)


I wanted to use a plain text so it would not have to execute a query in order to set the values, and set them via javascript (possibly) on the client's side.

**Comment by RonnyWeiss** [comment]
Hello

I understand what you did but these serttings are just for plugin developers so playong around with them can Not work. I would please you to use the query because It doesn't mather when you load the Code from Server. So it's easiest way to use the query 😉

Kind regards

Ronny
